name: Dev/QUA Deploy CI
on:
  # push:
  #   branches: [develop]
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [develop]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-20.04 #self-hosted
    steps:
      - name: Checkout to current repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build to publish
        run: dotnet publish ./aspnet-core/src/VinaCent.Blaze.Web.Mvc/VinaCent.Blaze.Web.Mvc.csproj -c Release # Must be change when clone this CI

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avzr -e "ssh -p ${{ secrets.SSH_PORT }}" ./aspnet-core/src/VinaCent.Blaze.Web.Mvc/bin/Release/net6.0/publish/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/deploy/apps/blaze.vinacent.com/

      - name: Restart Web Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo supervisorctl restart blaze.vinacent.com
